spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/access_control
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.nandan.auth.controller

logging:
  level:
    org:
      springframework:
        security=DEBUG:

# @TODO: Move secret to spring cloud and refresh the secret while doing it.
jwt:
  secret: ThisIsASuperSecretKeyThatShouldBeStoredSafely
  expiration: 86400000 # 1 day in milliseconds
